on:
  push:
    tags:
    - '*'

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, windows/386, windows/amd64, darwin/amd64 
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm, arm64]
        exclude:  
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
          - goarch: arm
            goos: windows
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.20
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.17.linux-amd64.tar.gz"
        binary_name: "flickr-meural-sync"
        extra_files: LICENSE README.md
        
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        build-args: CGO_ENABLED=0 GOOS=linux GOARCH=${{ matrix.goarch }}
        push: true
        tags: 
          - joooostb/flickr-meural-sync:latest
          - joooostb/flickr-meural-sync:${{ GITHUB_REF }}
