name: Docker
on:
  release: 
   types: [created]
jobs:
  build-matrix:
    name: Build & push containers
    runs-on: ubuntu-latest
    steps:
    - name: Get version from tag
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        build-args: arch=${{ matrix.goarch }}
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/flickr-meural-sync:${{steps.vars.outputs.tag}}
          ${{ secrets.DOCKERHUB_USERNAME }}/flickr-meural-sync:latest